### ISSUE TITLE
Instructions for building from source?

### ISSUE THREAD

**Issue by arschles** [lovethedrake/devdrake#24]
I noticed that Drake v0.9.0 supports v0.1.0 of the spec:

```console
~/src/kubernetes/devdrake(master*) » drake --version                                                                        aaronschlesinger@Aarons-Mac-mini

DevDrake version v0.9.0+bce7878 supports DrakeSpec v0.1.0
```

But the Drakefile (which is bc7160fdedfef68f6916d98ea7cb5e881c5534c5 as I write this) is at v0.2.0, so I want to build the CLI from source, manually. I'll give it a try and submit a PR if I can figure it out

**Comment by krancour** [comment]
This is an unfortunate confluence of two things... 1. breaking changes are expected in all pre-1.0.0 versions of the spec, so devdrake (and brigdrake) both support a single, discrete version instead of a range and 2. I have a build of brigdrake running in my cluster right now that builds _this_ project and is already supporting v0.2.0 of the spec. So... for the moment, this project is built by something else, but it can't build itself. This is a short-term problem. I should have a new release of devdrake buttoned up in the morning and the problem will be fixed... for now. But I think you've raised the point that there might be a chicken and egg problem that will arise, even if only periodically, and we should have an answer for that.
